"""The classifier's word lists and weights. Data, kept apart from the scoring code.

What this module is FOR: every word the intent classifier reacts to is written down
here, with its weight, so the whole behaviour can be read and argued with in one
place. Keys of ``KEYWORDS`` / ``PHRASES`` are ``Intent`` values (strings, so this
module imports nothing).

How the weights were set: a word that on its own names the question ("undo",
"evidence", "confident") weighs 3-4; a word that only leans ("alert", "real", "data")
weighs 1. ``MIN_SCORE`` is 2, so a single leaning word never earns an answer, and the
phrasing table in ``tests/test_assistant_intents.py`` is the regression check.

Action vocabulary is split three ways on purpose. ``ACTION_VERBS`` are the verbs that
ask for something to be done to a host ("kill", "block", "approve"); ``UNDO_VERBS``
ask for a change to be reversed ("rollback", "unblock"); ``QUESTION_ACTION_VERBS`` is
the subset that, inside a question ("did you kill it?"), means the user is asking what
was done. A verb is read as a request *unless* a question auxiliary comes before it
("did", "was", ...) or it is asked as advice ("should I", "how do I", "how to"): the
safe default for an ambiguous imperative is to treat it as a request and refuse it.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

__all__ = [
    "ACTION_VERBS",
    "ADVICE_SUBJECTS",
    "CASUAL_FORMS",
    "COMMAND_WORDS",
    "COMMON_WORDS",
    "FOLLOW_UP_TRIGGERS",
    "FOLLOW_UP_WORDS",
    "INJECTION_PATTERNS",
    "KEYWORDS",
    "NO_FUZZY_TARGETS",
    "MODALS",
    "PHRASES",
    "QUESTION_ACTION_VERBS",
    "QUESTION_AUXILIARIES",
    "SHELL_PATTERN",
    "UNDO_VERBS",
]

#: Chat shorthand and apostrophe-free contractions -> what they stand for.
CASUAL_FORMS: Mapping[str, str] = MappingProxyType(
    {
        "y": "why",
        "u": "you",
        "ur": "your",
        "r": "are",
        "hw": "how",
        "wat": "what",
        "wht": "what",
        "wut": "what",
        "wot": "what",
        "pls": "please",
        "plz": "please",
        "abt": "about",
        "cuz": "because",
        "coz": "because",
        "dunno": "do not know",
        "whats": "what is",
        "thats": "that is",
        "dont": "do not",
        "didnt": "did not",
        "doesnt": "does not",
        "cant": "can not",
        "couldnt": "could not",
        "wasnt": "was not",
        "isnt": "is not",
        "wont": "will not",
        "havent": "have not",
        "hasnt": "has not",
        "im": "i am",
        "lets": "let us",
        "wats": "what is",
    }
)

KEYWORDS: Mapping[str, Mapping[str, float]] = MappingProxyType(
    {
        "WHY_FLAGGED": {
            "why": 2.5,
            "flag": 3,
            "flags": 3,
            "flagged": 3,
            "flagging": 3,
            "alert": 1,
            "alerted": 2,
            "suspicious": 2,
            "reason": 2,
            "reasons": 2,
            "trigger": 3,
            "triggered": 3,
            "detected": 2,
            "detect": 2,
            "caught": 2,
            "fired": 2,
            "explain": 2,
        },
        "WHAT_HAPPENED": {
            "happened": 3,
            "happen": 3,
            "happening": 3,
            "occurred": 3,
            "occur": 2,
            "timeline": 3,
            "sequence": 2,
            "events": 2,
            "event": 1,
            "story": 2,
            "summary": 2,
            "summarize": 2,
            "summarise": 2,
            "overview": 2,
            "chronology": 3,
            "steps": 1,
            "files": 2,
            "touched": 2,
            "ip": 2,
            "port": 2,
            "connect": 2,
            "connected": 2,
            "root": 2,
        },
        "WHICH_PROCESS": {
            "process": 3,
            "processes": 3,
            "program": 3,
            "binary": 3,
            "executable": 3,
            "pid": 3,
            "app": 2,
            "application": 2,
            "who": 2,
            "culprit": 3,
            "responsible": 2,
            "actor": 2,
            "lineage": 2,
            "command": 2,
        },
        "HOW_SURE": {
            "sure": 3,
            "confident": 3,
            "confidence": 3,
            "certain": 3,
            "certainty": 3,
            "likely": 2,
            "likelihood": 2,
            "probability": 3,
            "probable": 2,
            "accurate": 2,
            "accuracy": 2,
            "reliable": 2,
            "score": 1,
            "uncertainty": 3,
            "uncertain": 2,
        },
        "WHAT_UNKNOWN": {
            "unknown": 3,
            "unknowns": 3,
            "gaps": 3,
            "gap": 3,
            "blind": 2,
            "blindspot": 3,
            "blindspots": 3,
            "missing": 2,
            "unclear": 2,
            "visibility": 3,
            "limits": 2,
            "limitations": 2,
            "hidden": 2,
            "shadow": 2,
            "unobserved": 3,
        },
        "WHAT_ACTION": {
            "action": 3,
            "actions": 3,
            "done": 2,
            "response": 3,
            "respond": 3,
            "responded": 3,
            "responding": 2,
            "taken": 2,
            "mitigation": 3,
            "mitigated": 4,
            "contained": 4,
            "containment": 3,
            "sentinel": 3,
            "receipt": 3,
            "receipts": 3,
            "approved": 3,
            "approval": 2,
            "handled": 3,
            "killed": 4,
            "blocked": 4,
            "terminated": 4,
            "quarantined": 4,
            "isolated": 4,
            "suspended": 4,
            "stopped": 3,
            "deleted": 3,
            "removed": 3,
            "remediated": 4,
            "measures": 2,
        },
        "HOW_TO_UNDO": {
            "undo": 4,
            "undone": 4,
            "revert": 4,
            "reverted": 3,
            "rollback": 4,
            "reverse": 3,
            "reversed": 3,
            "reversal": 3,
            "restore": 3,
            "restored": 3,
            "unblock": 4,
            "unsuspend": 4,
            "resume": 2,
            "release": 2,
            "lease": 3,
            "leases": 3,
            "expire": 2,
            "expires": 2,
            "expiry": 2,
            "expired": 2,
        },
        "FALSE_ALARM": {
            "false": 1,
            "benign": 3,
            "harmless": 3,
            "safe": 2,
            "legit": 3,
            "legitimate": 3,
            "innocent": 3,
            "noise": 2,
            "mistake": 2,
            "dangerous": 2,
            "danger": 2,
            "malicious": 2,
            "attack": 2,
            "hacked": 3,
            "compromised": 3,
            "real": 1,
            "worry": 2,
            "worried": 2,
            "threat": 2,
            "bad": 1,
            "stolen": 3,
            "steal": 3,
            "stole": 3,
            "malware": 3,
            "virus": 3,
            "serious": 3,
            "severity": 3,
            "severe": 3,
            "breach": 3,
            "breached": 3,
            "attacker": 2,
            "intruder": 2,
        },
        "EVIDENCE": {
            "evidence": 4,
            "proof": 3,
            "prove": 3,
            "proves": 3,
            "source": 2,
            "sources": 3,
            "digest": 3,
            "digests": 3,
            "hash": 2,
            "hashes": 2,
            "log": 2,
            "logs": 2,
            "raw": 2,
            "record": 1,
            "records": 1,
            "cite": 3,
            "citation": 3,
            "citations": 3,
            "data": 1,
            "telemetry": 2,
        },
        "HELP": {
            "help": 4,
            "commands": 3,
            "usage": 2,
            "options": 2,
            "menu": 3,
            "hello": 2,
            "hi": 2,
        },
        "ADVICE": {
            "recommend": 3,
            "recommendation": 3,
            "recommendations": 3,
            "advice": 4,
            "advise": 3,
        },
    }
)

PHRASES: Mapping[str, Mapping[str, float]] = MappingProxyType(
    {
        "WHY_FLAGGED": {
            "why did": 1,
            "what made": 2,
            "reason for": 2,
            "why is this": 1,
            "what triggered": 1,
            "what is wrong": 3,
        },
        "WHAT_HAPPENED": {
            "what happened": 2,
            "what did it do": 4,
            "going on": 3,
            "walk me through": 3,
            "tell me about": 2,
            "step by step": 2,
            "went on": 3,
        },
        "WHICH_PROCESS": {"which process": 2, "what process": 2, "who did": 2, "what program": 1},
        "HOW_SURE": {
            "how sure": 2,
            "how confident": 2,
            "how certain": 2,
            "how likely": 2,
            # "what does UNKNOWN mean" asks what the verdict means, which HOW_SURE's
            # abstention sentence answers; "unknown" alone would pick WHAT_UNKNOWN.
            "unknown mean": 5,
            "meaning of unknown": 5,
            "verdict mean": 4,
        },
        "WHAT_UNKNOWN": {"blind spot": 3, "blind spots": 3, "still in": 3, "still there": 3},
        "WHAT_ACTION": {
            "what did you do": 4,
            "did you do": 2,
            "do about": 4,
            "what was done": 4,
            "did pocketsec do": 4,
            "did you": 1,
        },
        "HOW_TO_UNDO": {
            "roll back": 4,
            "rolled back": 4,
            "put back": 3,
            "take back": 3,
            "roll it back": 4,
            "roll this back": 4,
            "roll that back": 4,
        },
        "FALSE_ALARM": {
            "false alarm": 4,
            "false positive": 4,
            "can i ignore": 4,
            "ignore this": 3,
            "ignore it": 3,
            "nothing to worry": 3,
            "should i worry": 3,
            "is it bad": 2,
            "for real": 3,
        },
        "EVIDENCE": {"show me": 1, "based on": 2, "how do you know": 3},
        "HELP": {
            "what can i ask": 4,
            "what can you do": 4,
            "how do i use": 4,
            "how does this work": 3,
        },
        "ADVICE": {
            "what should i do": 5,
            "what should we do": 5,
            "what do i do": 5,
            "what do we do": 5,
            "what to do": 4,
            "what now": 4,
            "next steps": 4,
            "next step": 4,
        },
    }
)

#: Imperatives that ask for something to be done to a host.
ACTION_VERBS: frozenset[str] = frozenset(
    {
        "kill",
        "block",
        "delete",
        "remove",
        "run",
        "execute",
        "terminate",
        "quarantine",
        "isolate",
        "ban",
        "stop",
        "disable",
        "uninstall",
        "wipe",
        "shutdown",
        "reboot",
        "restart",
        "suspend",
        "contain",
        "firewall",
        "erase",
        "purge",
        "nuke",
        "fix",
        "patch",
        "lock",
        "deny",
        "drop",
        "disconnect",
        "unplug",
        "blacklist",
        "blocklist",
        # Authority verbs. Each is one edit from a WHAT_ACTION past participle
        # ("approve" -> "approved"), so without this entry typo correction turned
        # "approve it" into a question about what was approved.
        "approve",
        "authorize",
        "authorise",
        "allow",
        "permit",
        "whitelist",
        "allowlist",
        "mitigate",
        "remediate",
        "handle",
        "respond",
        "dismiss",
    }
)
#: Imperatives that ask for a change to be reversed. Used as a request they keep the
#: HOW_TO_UNDO answer (which already says "I can't undo anything myself") and add the
#: general no-authority note.
UNDO_VERBS: frozenset[str] = frozenset(
    {
        "undo",
        "revert",
        "rollback",
        "reverse",
        "restore",
        "unblock",
        "unsuspend",
        "resume",
        "release",
        "unquarantine",
        "unlock",
        "reenable",
    }
)
#: A question auxiliary before an action verb makes it a question about the past or
#: about behaviour ("did you kill it?", "does it run as root?"), not a request.
QUESTION_AUXILIARIES: frozenset[str] = frozenset(
    {"did", "was", "were", "has", "have", "had", "does"}
)
#: "<modal> <subject> <verb>" with one of these subjects asks for advice ("should I
#: reboot?", "how do I fix this?"); with "you" it is a request ("can you kill it").
ADVICE_SUBJECTS: frozenset[str] = frozenset({"i", "we"})
#: The action verbs that, asked about, mean "what was done?".
QUESTION_ACTION_VERBS: frozenset[str] = frozenset(
    {"kill", "block", "terminate", "quarantine", "isolate", "suspend", "stop", "contain"}
)
#: Modals that, before "I"/"we", turn an action verb into a request for advice.
MODALS: frozenset[str] = frozenset(
    {"can", "could", "would", "will", "should", "do", "must", "shall", "might"}
)
#: Shell programs whose presence in a question makes it a request, never a question.
COMMAND_WORDS: frozenset[str] = frozenset(
    {"rm", "sudo", "chmod", "chown", "iptables", "pkill", "killall", "systemctl", "mkfs"}
)
#: Shell metacharacters and constructs: command chaining, pipes, substitution, redirection.
SHELL_PATTERN = r"[;|`<>]|\$\(|&&|\$\{"

#: Text that tries to give the explainer instructions or facts instead of a question.
INJECTION_PATTERNS: tuple[str, ...] = (
    r"\bignore\s+(all\s+|any\s+|the\s+|your\s+)?(previous|prior|above|earlier|preceding)",
    r"\bdisregard\b",
    r"\byou are now\b",
    r"\bsystem prompt\b",
    r"\bdeveloper mode\b",
    r"\bjailbreak",
    r"\bnew instructions?\b",
    r"\bpretend\b",
    r"\boverride\b",
    r"\[(obs|der|inf|cf|ext|unk|rec)\]",
    r"\bmark\s+(it|this|the alert|alert)\s+(as\s+)?(resolved|benign|safe|closed)\b",
)

#: A question made only of these words is a follow-up to the previous answer...
FOLLOW_UP_WORDS: frozenset[str] = frozenset(
    {
        "more",
        "tell",
        "me",
        "and",
        "else",
        "what",
        "go",
        "on",
        "continue",
        "details",
        "detail",
        "elaborate",
        "expand",
        "further",
        "keep",
        "going",
        "next",
        "also",
        "please",
        "anything",
        "is",
        "there",
        "about",
        "it",
        "explain",
        "does",
        "that",
        "mean",
        "meaning",
        "huh",
        "really",
        "so",
        "same",
        "for",
        "this",
        "one",
    }
)
#: ...provided it contains one of these.
FOLLOW_UP_TRIGGERS: frozenset[str] = frozenset(
    {
        "more",
        "else",
        "continue",
        "details",
        "detail",
        "elaborate",
        "expand",
        "further",
        "and",
        "go",
        "mean",
        "meaning",
        "huh",
        "really",
        "so",
        "same",
    }
)

#: Keywords that are never the target of a typo correction. Each is short or common
#: enough that real words sit one edit away ("style" / "stole", "fires" / "files",
#: "beach" / "breach"), measured with the word-list scan in docs/assistant.md. A
#: misspelt one goes unmatched and gets the help reply, which is the safe failure.
NO_FUZZY_TARGETS: frozenset[str] = frozenset(
    {
        "stole",
        "steal",
        "stolen",
        "files",
        "breach",
        "breached",
        "severe",
        "serious",
        "touched",
        "command",
        "connect",
        "connected",
        "attacker",
        "intruder",
        "explain",
        "advise",
    }
)

#: Everyday words that must never be "corrected" into a keyword: "please" is one
#: deletion from "lease", "where" one from "there". Typo tolerance is for misspelt
#: keywords, not for rewriting ordinary English into one.
COMMON_WORDS: frozenset[str] = frozenset(
    {
        "please",
        "there",
        "these",
        "those",
        "where",
        "which",
        "would",
        "could",
        "should",
        "about",
        "after",
        "other",
        "their",
        "while",
        "still",
        "being",
        "first",
        "thing",
        "things",
        "think",
        "thanks",
        "hello",
        "again",
        "every",
        "never",
        "maybe",
        "might",
        "right",
        "wrong",
        "place",
        "since",
        "under",
        "until",
        "above",
        "below",
        "leased",
        "reasoned",
        "season",
        "treason",
        "process",
        "proceed",
        "access",
        "files",
        "machine",
        "server",
        "system",
        "network",
        "really",
        "actually",
        "anything",
        # Everyday words one edit from a keyword, found by scanning a system word list
        # against the fuzzy targets (see docs/assistant.md). "locked" is not "blocked".
        "locked",
        "attach",
        "attached",
        "auction",
        "probably",
        "probe",
        "prose",
        "prone",
        "fixed",
        "filed",
        "fried",
        "fined",
        "handed",
        "handler",
        "handles",
        "defect",
        "store",
        "stored",
        "scope",
        "scare",
        "stops",
        "token",
        "tokens",
        "takes",
        "least",
        "leave",
        "leaves",
        "treat",
        "thread",
        "container",
        "killer",
        "storm",
        "stepped",
        "stems",
        "blend",
        "bland",
        "blond",
        "lively",
        "messing",
        "flaws",
        "throat",
        "shore",
        "swore",
        "dancer",
        "empire",
        "curtain",
        "linkage",
        "noose",
    }
)
